CREATE TABLE USERS_NOTES (
    NoteID INTEGER REFERENCES NOTES (NoteID),
    UserID INTEGER REFERENCES USERS (UserID) 
);

CREATE TABLE USERS (
    UserID    INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName TEXT,
    LastName  TEXT
);

CREATE TABLE NOTES (
    NoteID INTEGER  PRIMARY KEY AUTOINCREMENT,
    Date   DATETIME,
    Body   TEXT
);
