/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvc.view;

import java.text.ParseException;
import mvc.controller.AlertCntl;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Kaitlin
 */
public class AlertView extends javax.swing.JFrame {

	private AlertCntl alertCntl;

	/**
	 * Creates new form DateTimeScreen
	 */
	public AlertView(AlertCntl alertCntl) {
		this.alertCntl = alertCntl;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                DateTimeMainPanel = new javax.swing.JPanel();
                TitlePanel = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                DatePanel = new javax.swing.JPanel();
                DateLabel = new java.awt.Label();
                dateTextField = new java.awt.TextField();
                TimePanel = new javax.swing.JPanel();
                TimeLabel = new java.awt.Label();
                timeTextField = new java.awt.TextField();
                btnEnter = new javax.swing.JButton();
                btnCancel = new javax.swing.JButton();
                btnBack = new javax.swing.JButton();

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane1.setViewportView(jTable1);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel2.setText("Enter a date and time:");

                javax.swing.GroupLayout TitlePanelLayout = new javax.swing.GroupLayout(TitlePanel);
                TitlePanel.setLayout(TitlePanelLayout);
                TitlePanelLayout.setHorizontalGroup(
                        TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TitlePanelLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel2)
                                .addContainerGap(114, Short.MAX_VALUE))
                );
                TitlePanelLayout.setVerticalGroup(
                        TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitlePanelLayout.createSequentialGroup()
                                .addGap(0, 22, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                DateLabel.setText("Date");

                dateTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
                dateTextField.setName(""); // NOI18N
                dateTextField.setText("mm/dd/yyyy");
                dateTextField.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                dateTextFieldMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout DatePanelLayout = new javax.swing.GroupLayout(DatePanel);
                DatePanel.setLayout(DatePanelLayout);
                DatePanelLayout.setHorizontalGroup(
                        DatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DatePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                DatePanelLayout.setVerticalGroup(
                        DatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DatePanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(DatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(DatePanelLayout.createSequentialGroup()
                                                .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(DatePanelLayout.createSequentialGroup()
                                                .addComponent(DateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(26, 26, 26))))
                );

                TimeLabel.setText("Time");

                timeTextField.setText("HH:MM:SS");
                timeTextField.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                timeTextFieldMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout TimePanelLayout = new javax.swing.GroupLayout(TimePanel);
                TimePanel.setLayout(TimePanelLayout);
                TimePanelLayout.setHorizontalGroup(
                        TimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TimePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                TimePanelLayout.setVerticalGroup(
                        TimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TimePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(TimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(22, Short.MAX_VALUE))
                );

                btnEnter.setLabel("Enter");
                btnEnter.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEnterActionPerformed(evt);
                        }
                });

                btnCancel.setText("Cancel");
                btnCancel.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCancelActionPerformed(evt);
                        }
                });

                btnBack.setText("Back");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout DateTimeMainPanelLayout = new javax.swing.GroupLayout(DateTimeMainPanel);
                DateTimeMainPanel.setLayout(DateTimeMainPanelLayout);
                DateTimeMainPanelLayout.setHorizontalGroup(
                        DateTimeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DateTimeMainPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(DateTimeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(DateTimeMainPanelLayout.createSequentialGroup()
                                                .addComponent(btnEnter)
                                                .addGap(50, 50, 50)
                                                .addComponent(btnCancel)
                                                .addGap(50, 50, 50)
                                                .addComponent(btnBack))
                                        .addComponent(TimePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(35, Short.MAX_VALUE))
                );
                DateTimeMainPanelLayout.setVerticalGroup(
                        DateTimeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DateTimeMainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DateTimeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnEnter)
                                        .addComponent(btnCancel)
                                        .addComponent(btnBack))
                                .addGap(126, 126, 126))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(DateTimeMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(DateTimeMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void dateTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateTextFieldMouseClicked
	    dateTextField.setText("");
    }//GEN-LAST:event_dateTextFieldMouseClicked

    private void timeTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeTextFieldMouseClicked
	    timeTextField.setText("");
    }//GEN-LAST:event_timeTextFieldMouseClicked

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
		alertCntl.giveNavControl();
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
		String sDate = dateTextField.getText();
		String sTime = timeTextField.getText();
		String sCombine = sDate + " " + sTime;

		try {
			//Idea of code referenced from https://www.javatpoint.com/java-string-to-date
			Date finalDateTime = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").parse(sCombine);
			alertCntl.addDateTime(finalDateTime);
		} catch (ParseException e) {
			System.out.println(e.getMessage());
		}
        }//GEN-LAST:event_btnEnterActionPerformed

        private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
		dateTextField.setText("");
		timeTextField.setText("");
        }//GEN-LAST:event_btnCancelActionPerformed

//	private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) throws ParseException {
//		String sDate = dateTextField.getText();
//		String sTime = timeTextField.getText();
//		String sCombine = sDate + " " + sTime;
//
//		//Idea of code referenced from https://www.javatpoint.com/java-string-to-date
//		Date finalDateTime = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").parse(sCombine);
//	}
//	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
//		System.exit(0);
//	}
	/**
	 * @param args the command line arguments
	 */

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private java.awt.Label DateLabel;
        private javax.swing.JPanel DatePanel;
        private javax.swing.JPanel DateTimeMainPanel;
        private java.awt.Label TimeLabel;
        private javax.swing.JPanel TimePanel;
        private javax.swing.JPanel TitlePanel;
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnCancel;
        private javax.swing.JButton btnEnter;
        private java.awt.TextField dateTextField;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTable1;
        private java.awt.TextField timeTextField;
        // End of variables declaration//GEN-END:variables
}
