/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvc.view;

import mvc.controller.LoginCntl;

/**
 *
 * @author bryce
 */
public class CreateAccountView extends javax.swing.JFrame {

	private LoginCntl loginCntl;

	/**
	 * Creates new form CreateAccountUI
	 */
	public CreateAccountView(LoginCntl loginCntl) {
		this.loginCntl = loginCntl;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                titleLabel = new javax.swing.JLabel();
                firstNameLabel = new javax.swing.JLabel();
                lastNameLabel = new javax.swing.JLabel();
                firstNameField = new javax.swing.JTextField();
                lastNameField = new javax.swing.JTextField();
                resetButton = new javax.swing.JButton();
                cancelButton = new javax.swing.JButton();
                submitButton = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                titleLabel.setText("Create Account");

                firstNameLabel.setText("First Name:");

                lastNameLabel.setText("Last Name:");

                firstNameField.setText("Please Enter First Name");
                firstNameField.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                firstNameFieldMouseEntered(evt);
                        }
                });

                lastNameField.setText("Please Enter Last Name");
                lastNameField.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                lastNameFieldMouseEntered(evt);
                        }
                });

                resetButton.setText("Reset");
                resetButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                resetButtonActionPerformed(evt);
                        }
                });

                cancelButton.setText("Cancel");
                cancelButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelButtonActionPerformed(evt);
                        }
                });

                submitButton.setText("Submit");
                submitButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                submitButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lastNameLabel)
                                                        .addComponent(firstNameLabel))
                                                .addGap(98, 98, 98)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(firstNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                                        .addComponent(lastNameField)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(resetButton)
                                                .addGap(48, 48, 48)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(titleLabel)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(cancelButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(submitButton)))))
                                .addContainerGap(57, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titleLabel)
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(firstNameLabel)
                                        .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lastNameLabel)
                                        .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(resetButton)
                                        .addComponent(cancelButton)
                                        .addComponent(submitButton))
                                .addGap(37, 37, 37))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		loginCntl.showLoginUI(true);
		loginCntl.showCreateAccountUI(false);
        }//GEN-LAST:event_cancelButtonActionPerformed

        private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
		firstNameField.setText("");
		lastNameField.setText("");
        }//GEN-LAST:event_resetButtonActionPerformed

        private void firstNameFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstNameFieldMouseEntered
		firstNameField.setText("");
        }//GEN-LAST:event_firstNameFieldMouseEntered

        private void lastNameFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastNameFieldMouseEntered
		lastNameField.setText("");
        }//GEN-LAST:event_lastNameFieldMouseEntered

        private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
                loginCntl.createAccount(firstNameField.getText(), lastNameField.getText());
        }//GEN-LAST:event_submitButtonActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton cancelButton;
        private javax.swing.JTextField firstNameField;
        private javax.swing.JLabel firstNameLabel;
        private javax.swing.JTextField lastNameField;
        private javax.swing.JLabel lastNameLabel;
        private javax.swing.JButton resetButton;
        private javax.swing.JButton submitButton;
        private javax.swing.JLabel titleLabel;
        // End of variables declaration//GEN-END:variables
}
