/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvc.view;

import mvc.controller.NavCntl;

/**
 *
 * @author bryce
 */
public class NavView extends javax.swing.JFrame {

	private NavCntl navCntl;
	/**
	 * Creates new form NavView
	 */
	public NavView(NavCntl navCntl) {
		this.navCntl = navCntl;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                btnBack = new javax.swing.JButton();
                btnAlert = new javax.swing.JButton();
                btnNote = new javax.swing.JButton();
                labelTitle = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                btnBack.setText("Back");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });

                btnAlert.setText("Alert");

                btnNote.setText("Note");
                btnNote.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNoteActionPerformed(evt);
                        }
                });

                labelTitle.setText("Navigation");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnNote)
                                        .addComponent(btnAlert)
                                        .addComponent(btnBack)
                                        .addComponent(labelTitle))
                                .addContainerGap(173, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelTitle)
                                .addGap(48, 48, 48)
                                .addComponent(btnNote)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(btnAlert)
                                .addGap(69, 69, 69)
                                .addComponent(btnBack)
                                .addGap(21, 21, 21))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                navCntl.giveLoginControl();
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoteActionPerformed
                navCntl.giveNoteControl();
        }//GEN-LAST:event_btnNoteActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAlert;
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnNote;
        private javax.swing.JLabel labelTitle;
        // End of variables declaration//GEN-END:variables
}
