/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvc.view;

import mvc.controller.NoteListCntl;

/**
 *
 * @author bryce
 */
public class NoteListView extends javax.swing.JFrame {

	private NoteListCntl noteListCntl;
	/**
	 * Creates new form NoteListView
	 */
	public NoteListView(NoteListCntl noteListCntl) {
		this.noteListCntl = noteListCntl;
		initComponents();
		showNote();
	}

	
	private void showNote() {
		fieldNoteTitle.setText(noteListCntl.getNoteTitle());
		noteBody.setText(noteListCntl.getNoteBody());
	}
	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                btnBack = new javax.swing.JButton();
                labelTitle = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                noteBody = new javax.swing.JTextArea();
                btnSubmit = new javax.swing.JButton();
                fieldNoteTitle = new javax.swing.JTextField();
                btnNoteTitle = new javax.swing.JLabel();
                btnPrevious = new javax.swing.JButton();
                btnNext = new javax.swing.JButton();
                btnDelete = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                btnBack.setText("Back");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });

                labelTitle.setText("NoteList");

                noteBody.setColumns(20);
                noteBody.setRows(5);
                jScrollPane1.setViewportView(noteBody);

                btnSubmit.setText("Submit");
                btnSubmit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSubmitActionPerformed(evt);
                        }
                });

                btnNoteTitle.setText("Note Title:");

                btnPrevious.setText("Previous");
                btnPrevious.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnPreviousActionPerformed(evt);
                        }
                });

                btnNext.setText("Next");
                btnNext.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNextActionPerformed(evt);
                        }
                });

                btnDelete.setText("Delete");
                btnDelete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDeleteActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnNoteTitle)
                                                                .addGap(124, 124, 124)
                                                                .addComponent(fieldNoteTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(btnSubmit)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(btnPrevious)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(btnNext)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(btnDelete)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(btnBack))
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(174, 174, 174)
                                                .addComponent(labelTitle)))
                                .addGap(23, 23, 23))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fieldNoteTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnNoteTitle))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnBack)
                                        .addComponent(btnSubmit)
                                        .addComponent(btnPrevious)
                                        .addComponent(btnNext)
                                        .addComponent(btnDelete))
                                .addGap(22, 22, 22))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                noteListCntl.giveNavControl();
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
                noteListCntl.getNextNote();
		showNote();
        }//GEN-LAST:event_btnNextActionPerformed

        private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
                noteListCntl.getPreviousNote();
		showNote();
        }//GEN-LAST:event_btnPreviousActionPerformed

        private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
               noteListCntl.updateNote(fieldNoteTitle.getText(), noteBody.getText());
	       fieldNoteTitle.setText("");
	       noteBody.setText("");
        }//GEN-LAST:event_btnSubmitActionPerformed

        private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
                noteListCntl.deleteNote();
		fieldNoteTitle.setText("");
		noteBody.setText("");
        }//GEN-LAST:event_btnDeleteActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnDelete;
        private javax.swing.JButton btnNext;
        private javax.swing.JLabel btnNoteTitle;
        private javax.swing.JButton btnPrevious;
        private javax.swing.JButton btnSubmit;
        private javax.swing.JTextField fieldNoteTitle;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel labelTitle;
        private javax.swing.JTextArea noteBody;
        // End of variables declaration//GEN-END:variables
}
