/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.view;

import java.util.Date;
import javax.swing.JTextField;

/**
 *
 * @author sabrinamatteoli
 */
public class NoteView extends javax.swing.JFrame {

    /**
     * Creates new form NoteView
     */
    //pubic variable
    public String NoteInformation;
    public String DueDate;
    public String DueTime;
    
    public NoteView() {
        initComponents();
    }
    
    //get and set for NoteInformation
    
    public JTextField getNoteInformation(){
        return NewNoteField;
    }//getNoteInforamtion

    public void setNoteInformation(){
        NoteInformation = NewNoteField.getText();
    }//setNoteInformation
    
    //get and set for DueDate
    public JTextField getDueDate(){
        return NoteDate;
    }//getNoteInforamtion

    public void setDueDate(){
        DueDate = NoteDate.getText();
    }//setNoteInformation
    
    
    //get and set for DueTime
     public JTextField getDueTime(){
        return NoteTime;
    }//getNoteInforamtion

    public void setDueTime(){
        DueTime = NoteTime.getText();
    }//setNoteInformation
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                CreateNotePanel = new javax.swing.JPanel();
                CreateNewNoteLabel = new javax.swing.JLabel();
                DirectionsLabel = new javax.swing.JLabel();
                NewNoteField = new javax.swing.JTextField();
                SubmitButton = new javax.swing.JButton();
                CancelButton = new javax.swing.JButton();
                NoteDate = new javax.swing.JFormattedTextField();
                NoteTime = new javax.swing.JFormattedTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                CreateNewNoteLabel.setText("Create New Note");

                DirectionsLabel.setText("Enter your new note in the field below:");

                SubmitButton.setText("Submit");

                CancelButton.setText("Cancel");

                NoteDate.setText("YYYY-MM-DD");

                NoteTime.setText("HH:mm:ss");

                javax.swing.GroupLayout CreateNotePanelLayout = new javax.swing.GroupLayout(CreateNotePanel);
                CreateNotePanel.setLayout(CreateNotePanelLayout);
                CreateNotePanelLayout.setHorizontalGroup(
                        CreateNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CreateNotePanelLayout.createSequentialGroup()
                                .addGroup(CreateNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(CreateNotePanelLayout.createSequentialGroup()
                                                .addGap(145, 145, 145)
                                                .addComponent(CreateNewNoteLabel))
                                        .addGroup(CreateNotePanelLayout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(CreateNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(DirectionsLabel)
                                                        .addComponent(NewNoteField, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(33, Short.MAX_VALUE))
                        .addGroup(CreateNotePanelLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(CreateNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(SubmitButton)
                                        .addComponent(NoteDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(CreateNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(CreateNotePanelLayout.createSequentialGroup()
                                                .addComponent(NoteTime, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(CreateNotePanelLayout.createSequentialGroup()
                                                .addComponent(CancelButton)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                );
                CreateNotePanelLayout.setVerticalGroup(
                        CreateNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CreateNotePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(CreateNewNoteLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DirectionsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NewNoteField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(CreateNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(NoteDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(NoteTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(CreateNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(SubmitButton)
                                        .addComponent(CancelButton))
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CreateNotePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CreateNotePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 306, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton CancelButton;
        private javax.swing.JLabel CreateNewNoteLabel;
        private javax.swing.JPanel CreateNotePanel;
        private javax.swing.JLabel DirectionsLabel;
        private javax.swing.JTextField NewNoteField;
        private javax.swing.JFormattedTextField NoteDate;
        private javax.swing.JFormattedTextField NoteTime;
        private javax.swing.JButton SubmitButton;
        // End of variables declaration//GEN-END:variables
}
